revive_time: 600
revive_time_no_token: 86400

no_token_punishment:
  enabled: true
  type: SLOW_DIGGING
  duration: 3600
  message: "Du wurdest ohne Token wiederbelebt. Die Kraft des shrines ist nicht mit dir."
