name: ShrineRevive
version: '${version}'
main: com.itsziroy.shrinerevive.ShrineRevive
api-version: '1.20'
softdepend:
  - BukkitRedis

commands:
  shrine:
    usage: |
      /shrine create - Create a new shrine object
    permission: shrine.default
